In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [34]:
from sklearn.datasets import make_regression

In [35]:
X,y = make_regression(n_samples=100,n_features=1,noise=10)

In [36]:
X

array([[-1.0878835 ],
       [-0.2827503 ],
       [ 0.6365222 ],
       [-1.28362482],
       [-0.84476123],
       [ 0.7475358 ],
       [ 0.07863599],
       [ 0.7537778 ],
       [-2.68137365],
       [ 0.31090189],
       [ 2.29158804],
       [-1.0201444 ],
       [ 1.30420842],
       [ 0.66943127],
       [ 1.20168322],
       [-1.17733875],
       [ 1.72907559],
       [-1.50579995],
       [ 0.38426744],
       [-0.2472594 ],
       [-0.16814941],
       [ 0.14033942],
       [-3.05866764],
       [-0.26749761],
       [ 0.9234952 ],
       [ 0.03204638],
       [-0.91353591],
       [-0.08097149],
       [ 1.23285004],
       [-2.00022046],
       [-1.34708245],
       [-0.47140219],
       [ 0.94489527],
       [ 0.47024361],
       [-0.8219602 ],
       [-0.80990234],
       [ 0.94555783],
       [-0.52584871],
       [-1.6207397 ],
       [-3.61310853],
       [-1.27932216],
       [-1.2071613 ],
       [ 0.70460381],
       [-1.17582967],
       [ 1.69738722],
       [ 1

In [37]:
##Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.25,random_state=45)


In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
regression=LinearRegression()

In [40]:
regression.fit(X_train,Y_train)

LinearRegression()

In [41]:
coefficientslope=regression.coef_
print(coefficientslope)

[80.44988045]


In [42]:
iintercept=regression.intercept_
print(iintercept)

0.40088026438309754


In [43]:
plt.scatter(X_train,Y_train)

In [44]:
print("Intercept:",iintercept)
print("Slope:",coefficientslope)
plt.scatter(X_train,Y_train)
plt.plot(X_train,regression.predict(X_train))

Intercept: 0.40088026438309754
Slope: [80.44988045]


In [45]:
Y_pred=regression.predict(X_test)
Y_pred

array([ -87.11921707,  -22.34634743,  -85.41866445,  -45.73152349,
        -41.90358524,   64.10595519,   99.07033967, -129.98743501,
         51.60901514,    1.91760928,  -75.54555753,  -73.09297447,
       -119.88773268,   38.23192232,   40.90034742,  -67.56005943,
        -34.79407261,   61.04221404,  184.7588641 ,   22.40558821,
        104.40739981,   25.41290006,  -13.12671981,   31.31514978,
       -122.93559088])

In [46]:
#performance metrics
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [47]:
mse=mean_squared_error(Y_test,Y_pred)
mae=mean_absolute_error(Y_test,Y_pred)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

114.63951272632119
8.592846783641921
10.70698429653846


In [48]:
from sklearn.metrics import r2_score

In [61]:
from sklearn.metrics import r2_score
reg= LinearRegression()
reg.fit(X_train,Y_train)
Y_pred_p=reg.predict(X_test)
score=r2_score(Y_test,Y_pred_p)
print(score*100)

98.17957019000568


In [62]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error,r2_score
lasso = Lasso()
lasso.fit(X_train,Y_train)
Y_pred1=lasso.predict(X_test)
mae=mean_absolute_error(Y_test,Y_pred1)
score=r2_score(Y_test,Y_pred1)
print(mae)
print(score*100)
plt.scatter(Y_test,Y_pred1)

8.606129258585486
98.15579185657242


In [63]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error,r2_score
rid = Ridge()
rid.fit(X_train,Y_train)
Y_pred1=rid.predict(X_test)
mae=mean_absolute_error(Y_test,Y_pred1)
score=r2_score(Y_test,Y_pred1)
print(mae)
print(score*100)
plt.scatter(Y_test,Y_pred1)

8.615452983273283
98.15383472833352


In [52]:
# OLS Linear Regression
import statsmodels.api as sm


In [53]:
model = sm.OLS(Y_train,X_train).fit()

In [54]:
prediction=model.predict(X_test)
print(prediction)

[ -87.44702987  -22.72823682  -85.74789698  -46.09388943  -42.26914699
   63.65188979   98.58708373 -130.27945863   51.165383      1.51546275
  -75.88303277  -73.43249729 -120.18818819   37.79945824   40.46565557
  -67.90420149  -35.16556984   60.59070644  184.2040698    21.98633699
  103.91968814   24.99113813  -13.51630635   30.88846027 -123.23350184]


In [55]:
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.989
Model:                            OLS   Adj. R-squared (uncentered):              0.989
Method:                 Least Squares   F-statistic:                              6963.
Date:                Fri, 30 May 2025   Prob (F-statistic):                    5.98e-75
Time:                        17:55:50   Log-Likelihood:                         -282.13
No. Observations:                  75   AIC:                                      566.3
Df Residuals:                      74   BIC:                                      568.6
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [56]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()

In [64]:
#prediction for new data
regression.predict([[0.12346]])

array([10.3332225])