In [1]:
import numpy as np

In [6]:
arr1=np.array([[1,2,3,4,5],[2,4,5,6,7]])
print(arr1)
print(arr1.shape)

[[1 2 3 4 5]
 [2 4 5 6 7]]
(2, 5)


In [15]:
np.arange(0,12,2).reshape(6,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr2 =np.array([1,2,3,4,5])
arr3 =np.array([10,20,30,40,50])

print("addition is: " ,arr2+arr3)
print("subtraction is : ",arr2-arr3)
print("Multiplication is :",arr2*arr3)
print("Division is :",arr2/arr3)

addition is:  [11 22 33 44 55]
subtraction is :  [ -9 -18 -27 -36 -45]
Multiplication is : [ 10  40  90 160 250]
Division is : [0.1 0.1 0.1 0.1 0.1]


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)

	Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [28]:
print(arr[0,3])
print(arr[1,0:2])
print(arr[2,3])

4
[5 6]
12


In [30]:
arr[0,0]=100
print(arr)
arr[2:]=7
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  7   7   7   7]]


In [34]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean =np.mean(data)
print("Mean:",mean)

media = np.median(data)
print("Median:",media)

sd =np.std(data)
print(sd)


Mean: 5.5
Median: 5.5
2.8722813232690143


In [33]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
