In [2]:
import numpy as np

In [3]:
ar=np.arange(10,101,5)
print(ar)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [4]:
matrix = np.random.rand(5, 5)
print(matrix)


[[0.37393822 0.18836449 0.0992363  0.86577713 0.77153882]
 [0.99613294 0.25538123 0.71586827 0.59372845 0.2968425 ]
 [0.07864402 0.25272171 0.17064579 0.37652099 0.9402804 ]
 [0.27934417 0.15527483 0.03396731 0.96089401 0.78218206]
 [0.10162495 0.90221916 0.57868178 0.22890958 0.68425143]]


In [5]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
z1=np.ones(15)
z1[6]=7
print(z1)

[1. 1. 1. 1. 1. 1. 7. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
iden=np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
randam=np.random.randint(1,51,(3,3,3))
print(randam)


print(type(randam))

[[[11 46 29]
  [18 39 46]
  [41 32 16]]

 [[22 29  8]
  [43 22 44]
  [ 6  2  8]]

 [[42 25 15]
  [40 38 20]
  [48 25 14]]]
<class 'numpy.ndarray'>


In [12]:
arr1=np.random.randint(30,120,110)
arr1[arr1>50]=50
print(arr1)

[37 39 50 50 33 50 50 50 50 50 50 35 50 39 50 50 50 50 32 50 50 50 50 50
 50 33 50 50 50 35 50 50 50 50 50 50 50 50 50 50 50 50 50 42 37 50 50 33
 41 50 50 40 50 50 50 50 50 50 43 50 50 42 50 50 50 44 50 50 50 33 50 50
 40 50 50 32 50 45 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 39 50 50 32 50 50 50 50 50 50 50 50 50 39]


In [28]:
arr2=np.random.randint(10,120,16)
arr2[arr2>60]=7
print(arr2)

[ 7 55  7 19  7 18  7 56  7 21 43  7  7 12 38 33]


##### Find the indices of all nonzero elements in a given array?.


In [29]:
arr = np.array([0, 4, 0, 7, 0, 9])
indices = np.nonzero(arr)
print(indices)

(array([1, 3, 5]),)


##### Normalize an array (scale values between 0 and 1)?

In [30]:
arr = np.random.randint(10, 100, 10)
normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized_arr)

[1.         0.88888889 0.25       0.26388889 0.23611111 0.
 0.18055556 0.5        0.77777778 0.86111111]


In [31]:
arr4=np.random.randint(10,100,10)
normalized_arr1=arr-np.min(arr4)/np.max(arr4)-np.max(arr4)
print(normalized_arr1)

[ -9.33333333 -17.33333333 -63.33333333 -62.33333333 -64.33333333
 -81.33333333 -68.33333333 -45.33333333 -25.33333333 -19.33333333]


In [33]:
a= np.random.randint(10,40,(4,4))
b= np.random.randint(40,80,(4,4))
n= np.dot(a,b)
print(n)

[[8200 7134 6946 7432]
 [6712 6232 5880 6380]
 [9754 8519 8297 8927]
 [5300 4092 4414 4642]]


Simulate 1000 coin flips and count the number of heads (assuming 1 = heads, 0 = tails)?

In [34]:
flips = np.random.randint(0, 2, 1000)
num_heads = np.sum(flips)
print(f"Heads Count: {num_heads}")

Heads Count: 496


In [37]:
fipl=np.random.randint(0,1,1000)
head=np.sum(flips)
print(head)

496
